---
title: "Reproducing results in Coifman and Hirn's changing data paper"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r load, eval=FALSE, warning=FALSE, message=FALSE}
library(diffuseR)
library(scatterplot3d)
library(diffusionMap)
```

Here we seek to reproduce the results from Coifman and Hirn's 2013 paper that utilizes diffusion maps for the application of change detection. You can read more about their innovation [here](https://arxiv.org/abs/1209.0245). 

```{r, eval=FALSE, warning=FALSE, message=FALSE}
# Select two spectral images to compare 
X <- read.table("/hyperspectral/aug.dat", sep = ",")
Y <- read.table("/hyperspectral/oct_chg.dat", sep = ",")

# Get diffusion maps using our adapted diffusion maps method or traditional
D.X <- as.matrix(dist(X))
rm(X)
#d.X <- diffuseR::diffusionmapRsvd(D.X, numeigen = 10, t = 1)
d.X <- diffusionMap::diffuse(D.X, t = 1)
rm(D.X)
D.Y <- as.matrix(dist(Y))
rm(Y)
#d.Y <- diffuseR::diffusionmapRsvd(D.Y, numeigen = 10, t = 1)
d.Y <- diffusionMap::diffuse(D.Y, t = 1)
rm(D.Y)
VX <- d.X$X
EX <- diag(d.X$eigenvals)
VY <- d.Y$X
EY <- diag(d.Y$eigenvals)
# Compare
if (t < Inf){
  DMX <- VX %*% (EX^t)
  DMY_I <- VY %*% (EY^t)
  O <- crossprod(VY, VX)
  DMY <- DMY_I %*% O
}
# Change map 
if (t < Inf){
  chg_map <- sqrt(apply((DMX-DMY)^2, 1, sum))
} else {
  chg_map <- sqrt((VX[,1]-VY[,1])^2 + VX[,1] * VY[,1]*norm(as.matrix(VX[,1]-VY[,1]),type="2")^2)
}
chg_map <- matrix(chg_map,100,100)
chg_map_t <- apply(chg_map, 2, rev)
image(t(chg_map_t^.01), 
      axes = FALSE, 
      col = c(0,1,2,3,4,5,6,7,8),
      asp = 1)
```
