# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scaledist <- function(x, scale) {
    .Call(`_diffuseR_scaledist`, x, scale)
}

rcpp_hello_world <- function() {
    .Call(`_diffuseR_rcpp_hello_world`)
}

